"""Generate STRETCH and SQUASH tables for the logistic mixer.

Run once: python kolmo/_generate_tables.py > _table_output.py
Then paste the output into kolmo/_predictors.py.

Tables follow PAQ conventions:
  STRETCH[i] for i in 0..4095: Q12 prob → Q15 logit (×256 scale)
    logit = 256 × ln(p / (1-p)), p = (i+0.5)/4096
    range ≈ -2129..2129, stored as int16.

  SQUASH[i] for i in 0..4095: logit(×256) - 2048 → Q12 prob
    prob_q12 = round(4096 / (1 + exp(-logit/256)))
    index = logit + 2048, clamped to 0..4095.

This file is committed alongside the generated tables for auditability.
"""

import math


def _generate() -> tuple[tuple[int, ...], tuple[int, ...]]:
    N = 4096

    # --- STRETCH: Q12 prob → Q15 logit (×256, PAQ convention) ---
    stretch: list[int] = []
    for i in range(N):
        # Center of bucket i: p = (i + 0.5) / 4096
        p = (i + 0.5) / N
        # p is strictly in (0, 1) for all i, so ln(p/(1-p)) is always finite.
        logit = 256.0 * math.log(p / (1.0 - p))
        q = int(round(logit))
        # Clamp to int16 range just in case of any float edge case.
        if q < -32768:
            q = -32768
        elif q > 32767:
            q = 32767
        stretch.append(q)

    # --- SQUASH: logit (×256) → Q12 prob ---
    squash: list[int] = []
    for idx in range(N):
        logit = idx - 2048  # -2048..2047 in ×256 scale
        pk = 1.0 / (1.0 + math.exp(-logit / 256.0))
        q12 = int(round(pk * N))
        if q12 < 0:
            q12 = 0
        elif q12 > N - 1:
            q12 = N - 1
        squash.append(q12)

    return tuple(stretch), tuple(squash)


def main() -> None:
    stretch, squash = _generate()
    print("# fmt: off")
    print("# Generated by kolmo/_generate_tables.py — do not edit by hand.")
    print("# STRETCH[i] = round(256 * ln(((i+0.5)/4096) / (1 - (i+0.5)/4096)))")
    print(f"STRETCH: tuple[int, ...] = ({', '.join(str(v) for v in stretch)})")
    print()
    print("# SQUASH[i] = round(4096 / (1 + exp(-(i-2048)/256)))")
    print(f"SQUASH: tuple[int, ...] = ({', '.join(str(v) for v in squash)})")
    print("# fmt: on")


if __name__ == "__main__":
    main()
